-- ============================================================
-- Таблицы для библиотеки Центра речи «Будущее»
-- Выполни этот файл в Supabase SQL Editor один раз.
-- ============================================================

-- Книги
create table if not exists books (
  id            bigint generated by default as identity primary key,
  title         text not null,
  author        text not null default 'Неизвестный автор',
  description   text default '',
  available     boolean not null default true,
  cover_url     text default '',
  created_at    timestamptz not null default now()
);

alter table books enable row level security;

create policy "anon может читать книги"
  on books for select
  using (true);

create policy "anon может добавлять книги"
  on books for insert
  with check (true);

create policy "anon может обновлять книги"
  on books for update
  using (true);

create policy "anon может удалять книги"
  on books for delete
  using (true);

-- Заявки читателей
create table if not exists reader_requests (
  id          bigint generated by default as identity primary key,
  name        text not null default 'Читатель',
  message     text not null,
  created_at  timestamptz not null default now()
);

alter table reader_requests enable row level security;

create policy "anon может читать заявки"
  on reader_requests for select
  using (true);

create policy "anon может создавать заявки"
  on reader_requests for insert
  with check (true);

create policy "anon может удалять заявки"
  on reader_requests for delete
  using (true);
