-- ============================================================
-- Библиотека Центра речи «Будущее» — SQL для восстановления.
-- Выполни этот файл в Supabase → SQL Editor → New query → Run.
-- (Проект нужно предварительно создать заново, см. сообщение в чате.)
-- ============================================================

-- Книги
create table if not exists books (
  id            bigint generated by default as identity primary key,
  title         text not null,
  author        text not null default 'Неизвестный автор',
  description   text default '',
  available     boolean not null default true,
  cover_url     text default '',
  created_at    timestamptz not null default now()
);

alter table books enable row level security;

create policy "anon может читать книги"
  on books for select
  using (true);

create policy "anon может добавлять книги"
  on books for insert
  with check (true);

create policy "anon может обновлять книги"
  on books for update
  using (true)
  with check (true);

create policy "anon может удалять книги"
  on books for delete
  using (true);

-- Заявки читателей
create table if not exists reader_requests (
  id          bigint generated by default as identity primary key,
  name        text not null default 'Читатель',
  message     text not null,
  created_at  timestamptz not null default now()
);

alter table reader_requests enable row level security;

create policy "anon может читать заявки"
  on reader_requests for select
  using (true);

create policy "anon может создавать заявки"
  on reader_requests for insert
  with check (true);

create policy "anon может удалять заявки"
  on reader_requests for delete
  using (true);

-- Настройки сайта (график работы и т.п.) — одна строка с id = 1
create table if not exists site_settings (
  id          int primary key default 1,
  schedule    text not null default 'Понедельник: 9:00 – 16:00',
  updated_at  timestamptz not null default now()
);

insert into site_settings (id, schedule)
values (1, 'Понедельник: 9:00 – 16:00')
on conflict (id) do nothing;

alter table site_settings enable row level security;

create policy "все могут читать настройки"
  on site_settings for select
  using (true);

create policy "все могут менять настройки"
  on site_settings for update
  using (true)
  with check (true);
